using System;

namespace Model
{
	public enum CouponEffect
	{
		QUICK_CHANGE_WEAPON = 32768,
		QUICK_CHANGE_MAGAZINE = 16384,
		MEGA_HP10 = 8192,
		INCREASE_INVINCIBLE_TIME = 4096,
		BULLET_PROOF_VEST = 2048,
		FULLMETALJACKETAMMO = 1024,
		HOLLOW_POINT_AMMO = 512,
		C4_SPEED_KIT = 256,
		INCREASE_GRENADE_SLOT = 128,
		JACKETED_HELLOW_POINT_AMMO = 64,
		MEGA_HP5 = 32,
		BULLET_PROOF_VEST_PLUS = 16,
		HOLLOW_POINT_AMMO_PLUS = 8,
		BULLET_PROOF_VEST_METAL = 4,
		KETUPAT = 2
	}
}
