using System;

namespace PBServer.src.model.rooms
{
	public enum ROOM_STATE
	{
		ROOM_STATE_READY,
		ROOM_STATE_COUNTDOWN,
		ROOM_STATE_LOADING,
		ROOM_STATE_RENDEZVOUS,
		ROOM_STATE_PRE_BATTLE,
		ROOM_STATE_BATTLE,
		ROOM_STATE_BATTLE_END,
		ROOM_STATE_EMPTY
	}
}
